version: "3.9"

services:
  api:
    container_name: urlshortener_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.2-alpine3.17
    container_name: urlshortener_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: urlshortener
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
      - urlshortener_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
  live_reload:
    container_name: urlshortener_live_reload
    image: cosmtrek/air:v1.49.0
    # must be the same of mapped value
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    healthcheck:
      # port must be the same as the api container
      test: curl -fsS localhost:3000/health
    depends_on:
      db:
        condition: service_healthy

networks:
  urlshortener_network:
    driver: bridge

volumes:
  urlshortener_data:
    name: urlshortener_data

